### ISSUE TITLE
Add docker.sock

### ISSUE THREAD

**Issue by mariushosting** [aceberg/miniboard#1]
It would be great if we can add docker.sock to automatically add Docker Containers running on host without manually change the config board file.
-v /var/run/docker.sock:/var/run/docker.sock

**Comment by juanfrancisco227** [comment]
That be great indeed, I’m having the issue of updating the config file and after restarting the container nothing changes 🤦🏻‍♂️

**Comment by aceberg** [comment]
Done. There is an option now on `Edit panels` page to create panel from Docker automatically.
