### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by p0n1** [aceberg/miniboard#11]
I'm not sure if it's just me, but I'll record it here. I'm not sure of the exact reason. I have an instance that has been running since November 6th and is currently occupying over 6 GB of memory. I have added about 15 URLs.

I haven't restarted or killed it. Not sure if anything I can do to help on debug this.

**Comment by aceberg** [comment]
Thanks for letting me know! I looked at my instance and there it is too. 800Mb instead of supposed less than 20Mb. I'll try to fix it ASAP
