### ISSUE TITLE
more icons flexibility

### ISSUE THREAD

**Issue by tiloup42** [aceberg/miniboard#2]
I'm loving miniboard for its scanning feature and how easy it is to configure.

But i think i would gain popularity with these icons tweaks : 
- possibility yo modify Fav Icon / top left icon
- possibility to add icons to Panel titles
- possibility to use Fontawesome icons

I was using Homer for the moment , but its a bit to heavy for my test, while miniboard is a tad to bare :)

have a nice one !

**Comment by aceberg** [comment]
Thanks)
I'll think about Fontawesome icons, the others are not in the roadmap though.
