### ISSUE TITLE
All of my panels and tabs have disappeared

### ISSUE THREAD

**Issue by haitispaceagency** [aceberg/miniboard#6]
Not sure how to provide any further information to help. Everything is just gone despite the rest of the app working. It loads fine and I add stuff to it and everything, but all my previous settings are gone.

**Comment by aceberg** [comment]
> Not sure how to provide any further information to help. Everything is just gone despite the rest of the app working. It loads fine and I add stuff to it and everything, but all my previous settings are gone.

There can be 2 explanations for this:
1. Bug in miniboard
2. Bug in your setup

As no one else reported this yet, and I'm using 3 instances of miniboard myself, let's start with the most likely mistake:
- If you are using Docker and change data inside the container, it will disappear after container is restarted. To prevent this, mount `/data/miniboard` somewhere permanent.

If that's not the case, I need more info:
1. Are you using Docker or other setup method?
2. Was `config.yaml` also affected? Did the theme settings disappeared too?
3. Did `board.yaml` file disappeared, or was it empty, or was there some of your config, but not all?
4. What `docker logs miniboard` says?

**Comment by aceberg** [comment]
No reports on this issue in 2 months. Closing.
