### ISSUE TITLE
Investigation - Unable to load GUI

### ISSUE THREAD

**Issue by ServerGeek82** [aceberg/miniboard#7]
docker log snippet

2023/10/04 14:40:55 ERROR: listen tcp 192.168.0.228:8959: bind: cannot assign requested address
2023/10/04 14:41:56 INFO: starting web gui with config /data/miniboard/config.yaml
2023/10/04 14:41:56 INFO: writing new Board file to /data/miniboard/board.yaml
2023/10/04 14:41:56 =================================== 
2023/10/04 14:41:56 Web GUI at http://192.168.0.228:8959
2023/10/04 14:41:56 =================================== 
2023/10/04 14:41:56 ERROR: listen tcp 192.168.0.228:8959: bind: cannot assign requested address

config.yaml

btnwidth: 180px
color: dark
coloroff: '#ff7171'
coloron: '#89ff89'
host: "192.168.0.228"
port: "8849"
theme: solar
webrefresh: "60"

Network config of compose file:

    networks:
      - traefik-net
      - mxprod01-net

networks:
  traefik-net:
    external: true
  mxprod01-net:
    external: true

Im curious if IPV6 is a possibility of an issue. I have tried changing ports to known unused ports. Have attempted removing config and rebuilding. 

I have 40+ containers running with no issues.

**Comment by aceberg** [comment]
Hi! You said on reddit that you solved the issue. 

I think the problem was `host: "192.168.0.228"`, it should be `0.0.0.0` if running in docker.
